print("\t\t\tUSER INFORMATION")
name = input("enter your name :")
age = input("enter your age :")
dob = input("enter your dob :")
phone = input("enter your phone number :")
gender = input("enter your gender :")
qualification = input("enter your qualification :")
address = input("enter your address :")
salary = input("enter your salary :")
state = input("enter your state :")
country = input("enter your country :")
print("\n")
print("\t\t\tDETAILS")
print(f"name = {name}")
print(f"age = {age}")
print(f"dob = {dob}")
print(f"phone = {phone}")
print(f"gender = {gender}")
print(f"qualification = {qualification}")
print(f"address = {address}")
print(f"salary = {salary}")
print(f"state = {state}")
print(f"country = {country}")